@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.autobotany.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;