@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.autobotany.contents;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;