@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.autobotany.crop.condition;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;