@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.autobotany.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;