@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.autobotany.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;