@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.autobotany.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;